name: "CI"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "yarn install"
      run: yarn install

    - name: "yarn run build"
      run: yarn run build

    - name: "yarn run test"
      run: yarn run test
