name: "action-test"
on: # rebuild any PRs and main branch changes
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        github-status-context: "Custom Name"
        checklist-item-1: "item one"
        checklist-item-2: "item two"
        checklist-item-3: "item three"
